variable "component" {}
variable "env" {}
variable "tags" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "subnets" {}
variable "vpc_id" {}
variable "bastion_cidr" {}